spring:
  application:
    name: soccer

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/soccer
    username: root
    password: 1234

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
    database: mysql
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  redis:
    host: localhost
    port: 6379

  jwt: # Base64로 인코딩이 안된 16진수 문자열 - getSecretKey 방식
    secret-key: "4fcb69786e14762d0e2b86561fca5bfa258ff929f658dcfbe2a535285ffce3ad"
    # c3ByaW5nLWJvb3QtYXBpLWp3dC1zZWNyZXQta2V5LXN1cGVyLXNlY3JldC15ZXMteWVzLXllcy0yNAo=   >>> Base64로 인코딩된 문자열 - setSecretKey 방식

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 216109154511553a2ac3e876eb1362fb  # 카카오 개발자 콘솔에서 발급받은 REST API Key
            client-secret: X4zWLUAMkWehfT2AoSaTePNs3nrolWpj  # 카카오 앱의 비밀키 (선택 사항)
            client-authentication-method: client_secret_post
            redirect-uri: "http://127.0.0.1:5500/main.html"  # Redirect URI 설정 (예: http://localhost:8080/login/oauth2/code/kakao)
            authorization-grant-type: authorization_code  # 권한 부여 유형 (코드 기반 인증)
            scope: account_email  # 요청할 권한 범위
#            client-name: Kakao  # 클라이언트 이름 (선택 사항)
          naver:
            client-id: INK5Ren5sHqo2XHb5Bw2  # 카카오 개발자 콘솔에서 발급받은 REST API Key
            client-secret: VYMufxc_Nw  # 카카오 앱의 비밀키 (선택 사항)
            redirect-uri: "http://127.0.0.1:5500/main.html"  # Redirect URI 설정 (예: http://localhost:8080/login/oauth2/code/naver)
            authorization-grant-type: authorization_code  # 권한 부여 유형 (코드 기반 인증)
            scope: email  # 요청할 권한 범위
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize  # OAuth2 인증 흐름에서 사용자를 카카오 인증 서버로 리다이렉트하기 위한 URL
            token-uri: https://kauth.kakao.com/oauth/token  # 카카오 토큰 발급 URI
            user-info-uri: https://kapi.kakao.com/v2/user/me  # 카카오 사용자 정보 조회 URI
            user-name-attribute: id  # 사용자 정보에서 id를 기준으로 사용자 정보 제공
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize  # 카카오 인증 서버 URI
            token-uri: https://nid.naver.com/oauth2.0/token  # 카카오 토큰 발급 URI
            user-info-uri: https://openapi.naver.com/v1/nid/me  # 카카오 사용자 정보 조회 URI
            user-name-attribute: response  # 사용자 정보에서 id를 기준으로 사용자 정보 제공

#    refresh-token-validity-in-seconds: 1209630 # 14일
#    access-token-validity-in-seconds: 43200 # 12시간
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.example.soccer: DEBUG
#    org.hibernate: DEBUG
#    com.zaxxer.hikari: DEBUG
#    com.p6spy: DEBUG
